import img_01 from "../../assets/img/portfolio/img_01.png";
import img_02 from "../../assets/img/portfolio/img_02.png";
import img_03 from "../../assets/img/portfolio/img_03.png";
import img_04 from "../../assets/img/portfolio/img_04.png";
import img_05 from "../../assets/img/portfolio/img_05.png";
import img_06 from "../../assets/img/portfolio/img_06.png";
import img_07 from "../../assets/img/portfolio/img_07.png";
import img_08 from "../../assets/img/portfolio/img_08.png";
import img_09 from "../../assets/img/portfolio/img_09.png";
import img_10 from "../../assets/img/portfolio/img_10.png";
import img_11 from "../../assets/img/portfolio/img_11.png";
import img_12 from "../../assets/img/portfolio/img_12.png";

export const nav = [
  {
    id: 1,
    name: "Commerical",
    sub_Category: [
      {
        id: 1,
        name: "Architectural",
        types: [
          { id: 1, name: "Light Interior" },
          { id: 2, name: "Dark Interior" },
          { id: 3, name: "Traditional" },
          { id: 4, name: "Modern" },
        ],
      },

      {
        id: 2,
        name: "1-2 rooms",
        types: [
          { id: 1, name: "Light Interior" },
          { id: 2, name: "Dark Interior" },
          { id: 3, name: "Traditional" },
          { id: 4, name: "Modern" },
        ],
      },

      {
        id: 3,
        name: "3-4 rooms",
        types: [
          { id: 1, name: "Light Interior" },
          { id: 2, name: "Dark Interior" },
          { id: 3, name: "Traditional" },
          { id: 4, name: "Modern" },
        ],
      },

      {
        id: 4,
        name: "more rooms",
        types: [
          { id: 1, name: "Light Interior" },
          { id: 2, name: "Dark Interior" },
          { id: 3, name: "Traditional" },
          { id: 4, name: "Modern" },
        ],
      },
    ],
  },

  {
    id: 2,
    name: "Residential",
    sub_Category: [
      {
        id: 1,
        name: "Architectural",
        types: [
          { id: 1, name: "Light Interior" },
          { id: 2, name: "Dark Interior" },
          { id: 3, name: "Traditional" },
          { id: 4, name: "Modern" },
        ],
      },

      {
        id: 2,
        name: "1-2 rooms",
        types: [
          { id: 1, name: "Light Interior" },
          { id: 2, name: "Dark Interior" },
          { id: 3, name: "Traditional" },
          { id: 4, name: "Modern" },
        ],
      },

      {
        id: 3,
        name: "3-4 rooms",
        types: [
          { id: 1, name: "Light Interior" },
          { id: 2, name: "Dark Interior" },
          { id: 3, name: "Traditional" },
          { id: 4, name: "Modern" },
        ],
      },

      {
        id: 4,
        name: "more rooms",
        types: [
          { id: 1, name: "Light Interior" },
          { id: 2, name: "Dark Interior" },
          { id: 3, name: "Traditional" },
          { id: 4, name: "Modern" },
        ],
      },
    ],
  },
];


export const projectsRoom = [
  {
    id: 1,
    title: "Living room"
  },
  {
    id: 2,
    title: "kitchen"
  },
  {
    id: 3,
    title: "Bedroom"
  },
  {
    id: 4,
    title: "Bathroom"
  },
  {
    id: 5,
    title: "Balcony"
  }
];


export const data = [
  {
    id: 1,
    categoryId: 1,
    subCategoryId: 1,
    typeId: 1,
    img: img_01,
    hover_Name: "Minimalist Interior Design",
    hover_About: "Lorem ipsum dolor sit amet consectetur. Euismod commodo ut mus urna justo vel Euismod commodo ut mus urna justo vel.",
    hover_See: "See Project",
    title: "Modern Minimalistic Interior Design",
    subTitle: "Lorem ipsum dolor sit amet consectetur. Integer sit vel quisque laoreet lacus at. Adipiscing lacinia sit platea a nunc libero.",
    description: "Lorem ipsum dolor sit amet consectetur. Integer sit vel quisque laoreet lacus at. Adipiscing lacinia sit platea a nunc libero. In ut adipiscing urna pellentesque amet varius posuere quis. Lorem ipsum dolor sit amet consectetur. Integer sit vel quisque laoreet lacus at. ",
    location: "Czech Republic, Prague",
    size: "80 m2",
    date: "04 / 2024",
    isFavorite: true,
    images: [
      {id: 1, img: img_01, roomId: 1, isFavorite: false},
      {id: 2, img: img_02, roomId: 2, isFavorite: false},
      {id: 3, img: img_03, roomId: 3, isFavorite: false},
    ]
  },

  {
    id: 2,
    categoryId: 2,
    subCategoryId: 2,
    typeId: 2,
    img: img_04,
    hover_Name: "Minimalist Interior Design",
    hover_About: "Lorem ipsum dolor sit amet consectetur. Euismod commodo ut mus urna justo vel Euismod commodo ut mus urna justo vel.",
    hover_See: "See Project",
    title: "Modern Minimalistic Interior Design",
    subTitle: "Lorem ipsum dolor sit amet consectetur. Integer sit vel quisque laoreet lacus at. Adipiscing lacinia sit platea a nunc libero.",
    description: "Lorem ipsum dolor sit amet consectetur. Integer sit vel quisque laoreet lacus at. Adipiscing lacinia sit platea a nunc libero. In ut adipiscing urna pellentesque amet varius posuere quis. Lorem ipsum dolor sit amet consectetur. Integer sit vel quisque laoreet lacus at. ",
    location: "Czech Republic, Prague",
    size: "80 m2",
    date: "04 / 2024",
    isFavorite: true,
    images: [
      {id: 1, img: img_04,roomId: 1, isFavorite: false},
      {id: 2, img: img_05,roomId: 2, isFavorite: false},
      {id: 3, img: img_06,roomId: 3, isFavorite: false},
    ]
  },
  {
    id: 3,
    categoryId: 2,
    subCategoryId: 2,
    typeId: 2,
    img: img_04,
    hover_Name: "Minimalist Interior Design",
    hover_About: "Lorem ipsum dolor sit amet consectetur. Euismod commodo ut mus urna justo vel Euismod commodo ut mus urna justo vel.",
    hover_See: "See Project",
    title: "Modern Minimalistic Interior Design",
    subTitle: "Lorem ipsum dolor sit amet consectetur. Integer sit vel quisque laoreet lacus at. Adipiscing lacinia sit platea a nunc libero.",
    description: "Lorem ipsum dolor sit amet consectetur. Integer sit vel quisque laoreet lacus at. Adipiscing lacinia sit platea a nunc libero. In ut adipiscing urna pellentesque amet varius posuere quis. Lorem ipsum dolor sit amet consectetur. Integer sit vel quisque laoreet lacus at. ",
    location: "Czech Republic, Prague",
    size: "80 m2",
    date: "04 / 2024",
    isFavorite: true,
    images: [
      {id: 1, img: img_04,roomId: 1, isFavorite: false},
      {id: 2, img: img_05,roomId: 2, isFavorite: false},
      {id: 3, img: img_06,roomId: 3, isFavorite: false},
    ]
  },
  {
    id: 4,
    categoryId: 2,
    subCategoryId: 2,
    typeId: 2,
    img: img_04,
    hover_Name: "Minimalist Interior Design",
    hover_About: "Lorem ipsum dolor sit amet consectetur. Euismod commodo ut mus urna justo vel Euismod commodo ut mus urna justo vel.",
    hover_See: "See Project",
    title: "Modern Minimalistic Interior Design",
    subTitle: "Lorem ipsum dolor sit amet consectetur. Integer sit vel quisque laoreet lacus at. Adipiscing lacinia sit platea a nunc libero.",
    description: "Lorem ipsum dolor sit amet consectetur. Integer sit vel quisque laoreet lacus at. Adipiscing lacinia sit platea a nunc libero. In ut adipiscing urna pellentesque amet varius posuere quis. Lorem ipsum dolor sit amet consectetur. Integer sit vel quisque laoreet lacus at. ",
    location: "Czech Republic, Prague",
    size: "80 m2",
    date: "04 / 2024",
    isFavorite: true,
    images: [
      {id: 1, img: img_04,roomId: 1, isFavorite: false},
      {id: 2, img: img_05,roomId: 2, isFavorite: false},
      {id: 3, img: img_06,roomId: 3, isFavorite: false},
    ]
  },
  {
    id: 5,
    categoryId: 2,
    subCategoryId: 2,
    typeId: 2,
    img: img_02,
    hover_Name: "Minimalist Interior Design",
    hover_About: "Lorem ipsum dolor sit amet consectetur. Euismod commodo ut mus urna justo vel Euismod commodo ut mus urna justo vel.",
    hover_See: "See Project",
    title: "Modern Minimalistic Interior Design",
    subTitle: "Lorem ipsum dolor sit amet consectetur. Integer sit vel quisque laoreet lacus at. Adipiscing lacinia sit platea a nunc libero.",
    description: "Lorem ipsum dolor sit amet consectetur. Integer sit vel quisque laoreet lacus at. Adipiscing lacinia sit platea a nunc libero. In ut adipiscing urna pellentesque amet varius posuere quis. Lorem ipsum dolor sit amet consectetur. Integer sit vel quisque laoreet lacus at. ",
    location: "Czech Republic, Prague",
    size: "80 m2",
    date: "04 / 2024",
    isFavorite: true,
    images: [
      {id: 1, img: img_04,roomId: 1, isFavorite: false},
      {id: 2, img: img_05,roomId: 2, isFavorite: false},
      {id: 3, img: img_06,roomId: 3, isFavorite: false},
    ]
  },
  {
    id: 6,
    categoryId: 2,
    subCategoryId: 2,
    typeId: 2,
    img: img_04,
    hover_Name: "Minimalist Interior Design",
    hover_About: "Lorem ipsum dolor sit amet consectetur. Euismod commodo ut mus urna justo vel Euismod commodo ut mus urna justo vel.",
    hover_See: "See Project",
    title: "Modern Minimalistic Interior Design",
    subTitle: "Lorem ipsum dolor sit amet consectetur. Integer sit vel quisque laoreet lacus at. Adipiscing lacinia sit platea a nunc libero.",
    description: "Lorem ipsum dolor sit amet consectetur. Integer sit vel quisque laoreet lacus at. Adipiscing lacinia sit platea a nunc libero. In ut adipiscing urna pellentesque amet varius posuere quis. Lorem ipsum dolor sit amet consectetur. Integer sit vel quisque laoreet lacus at. ",
    location: "Czech Republic, Prague",
    size: "80 m2",
    date: "04 / 2024",
    isFavorite: true,
    images: [
      {id: 1, img: img_04,roomId: 1, isFavorite: false},
      {id: 2, img: img_05,roomId: 2, isFavorite: false},
      {id: 3, img: img_06,roomId: 3, isFavorite: false},
    ]
  },
  {
    id: 7,
    categoryId: 2,
    subCategoryId: 2,
    typeId: 2,
    img: img_08,
    hover_Name: "Minimalist Interior Design",
    hover_About: "Lorem ipsum dolor sit amet consectetur. Euismod commodo ut mus urna justo vel Euismod commodo ut mus urna justo vel.",
    hover_See: "See Project",
    title: "Modern Minimalistic Interior Design",
    subTitle: "Lorem ipsum dolor sit amet consectetur. Integer sit vel quisque laoreet lacus at. Adipiscing lacinia sit platea a nunc libero.",
    description: "Lorem ipsum dolor sit amet consectetur. Integer sit vel quisque laoreet lacus at. Adipiscing lacinia sit platea a nunc libero. In ut adipiscing urna pellentesque amet varius posuere quis. Lorem ipsum dolor sit amet consectetur. Integer sit vel quisque laoreet lacus at. ",
    location: "Czech Republic, Prague",
    size: "80 m2",
    date: "04 / 2024",
    isFavorite: true,
    images: [
      {id: 1, img: img_04,roomId: 1, isFavorite: false},
      {id: 2, img: img_05,roomId: 2, isFavorite: false},
      {id: 3, img: img_06,roomId: 3, isFavorite: false},
    ]
  },
  {
    id: 8,
    categoryId: 2,
    subCategoryId: 2,
    typeId: 2,
    img: img_04,
    hover_Name: "Minimalist Interior Design",
    hover_About: "Lorem ipsum dolor sit amet consectetur. Euismod commodo ut mus urna justo vel Euismod commodo ut mus urna justo vel.",
    hover_See: "See Project",
    title: "Modern Minimalistic Interior Design",
    subTitle: "Lorem ipsum dolor sit amet consectetur. Integer sit vel quisque laoreet lacus at. Adipiscing lacinia sit platea a nunc libero.",
    description: "Lorem ipsum dolor sit amet consectetur. Integer sit vel quisque laoreet lacus at. Adipiscing lacinia sit platea a nunc libero. In ut adipiscing urna pellentesque amet varius posuere quis. Lorem ipsum dolor sit amet consectetur. Integer sit vel quisque laoreet lacus at. ",
    location: "Czech Republic, Prague",
    size: "80 m2",
    date: "04 / 2024",
    isFavorite: true,
    images: [
      {id: 1, img: img_04,roomId: 1, isFavorite: false},
      {id: 2, img: img_05,roomId: 2, isFavorite: false},
      {id: 3, img: img_06,roomId: 3, isFavorite: false},
    ]
  },
  {
    id: 9,
    categoryId: 2,
    subCategoryId: 2,
    typeId: 2,
    img: img_06,
    hover_Name: "Minimalist Interior Design",
    hover_About: "Lorem ipsum dolor sit amet consectetur. Euismod commodo ut mus urna justo vel Euismod commodo ut mus urna justo vel.",
    hover_See: "See Project",
    title: "Modern Minimalistic Interior Design",
    subTitle: "Lorem ipsum dolor sit amet consectetur. Integer sit vel quisque laoreet lacus at. Adipiscing lacinia sit platea a nunc libero.",
    description: "Lorem ipsum dolor sit amet consectetur. Integer sit vel quisque laoreet lacus at. Adipiscing lacinia sit platea a nunc libero. In ut adipiscing urna pellentesque amet varius posuere quis. Lorem ipsum dolor sit amet consectetur. Integer sit vel quisque laoreet lacus at. ",
    location: "Czech Republic, Prague",
    size: "80 m2",
    date: "04 / 2024",
    isFavorite: true,
    images: [
      {id: 1, img: img_04,roomId: 1, isFavorite: false},
      {id: 2, img: img_05,roomId: 2, isFavorite: false},
      {id: 3, img: img_06,roomId: 3, isFavorite: false},
    ]
  },
  {
    id: 10,
    categoryId: 2,
    subCategoryId: 2,
    typeId: 2,
    img: img_01,
    hover_Name: "Minimalist Interior Design",
    hover_About: "Lorem ipsum dolor sit amet consectetur. Euismod commodo ut mus urna justo vel Euismod commodo ut mus urna justo vel.",
    hover_See: "See Project",
    title: "Modern Minimalistic Interior Design",
    subTitle: "Lorem ipsum dolor sit amet consectetur. Integer sit vel quisque laoreet lacus at. Adipiscing lacinia sit platea a nunc libero.",
    description: "Lorem ipsum dolor sit amet consectetur. Integer sit vel quisque laoreet lacus at. Adipiscing lacinia sit platea a nunc libero. In ut adipiscing urna pellentesque amet varius posuere quis. Lorem ipsum dolor sit amet consectetur. Integer sit vel quisque laoreet lacus at. ",
    location: "Czech Republic, Prague",
    size: "80 m2",
    date: "04 / 2024",
    isFavorite: true,
    images: [
      {id: 1, img: img_04,roomId: 1, isFavorite: false},
      {id: 2, img: img_05,roomId: 2, isFavorite: false},
      {id: 3, img: img_06,roomId: 3, isFavorite: false},
    ]
  },
  {
    id: 11,
    categoryId: 2,
    subCategoryId: 2,
    typeId: 2,
    img: img_07,
    hover_Name: "Minimalist Interior Design",
    hover_About: "Lorem ipsum dolor sit amet consectetur. Euismod commodo ut mus urna justo vel Euismod commodo ut mus urna justo vel.",
    hover_See: "See Project",
    title: "Modern Minimalistic Interior Design",
    subTitle: "Lorem ipsum dolor sit amet consectetur. Integer sit vel quisque laoreet lacus at. Adipiscing lacinia sit platea a nunc libero.",
    description: "Lorem ipsum dolor sit amet consectetur. Integer sit vel quisque laoreet lacus at. Adipiscing lacinia sit platea a nunc libero. In ut adipiscing urna pellentesque amet varius posuere quis. Lorem ipsum dolor sit amet consectetur. Integer sit vel quisque laoreet lacus at. ",
    location: "Czech Republic, Prague",
    size: "80 m2",
    date: "04 / 2024",
    isFavorite: true,
    images: [
      {id: 1, img: img_04,roomId: 1, isFavorite: false},
      {id: 2, img: img_05,roomId: 2, isFavorite: false},
      {id: 3, img: img_06,roomId: 3, isFavorite: false},
    ]
  },
  {
    id: 12,
    categoryId: 2,
    subCategoryId: 2,
    typeId: 2,
    img: img_09,
    hover_Name: "Minimalist Interior Design",
    hover_About: "Lorem ipsum dolor sit amet consectetur. Euismod commodo ut mus urna justo vel Euismod commodo ut mus urna justo vel.",
    hover_See: "See Project",
    title: "Modern Minimalistic Interior Design",
    subTitle: "Lorem ipsum dolor sit amet consectetur. Integer sit vel quisque laoreet lacus at. Adipiscing lacinia sit platea a nunc libero.",
    description: "Lorem ipsum dolor sit amet consectetur. Integer sit vel quisque laoreet lacus at. Adipiscing lacinia sit platea a nunc libero. In ut adipiscing urna pellentesque amet varius posuere quis. Lorem ipsum dolor sit amet consectetur. Integer sit vel quisque laoreet lacus at. ",
    location: "Czech Republic, Prague",
    size: "80 m2",
    date: "04 / 2024",
    isFavorite: true,
    images: [
      {id: 1, img: img_04,roomId: 1, isFavorite: false},
      {id: 2, img: img_05,roomId: 2, isFavorite: false},
      {id: 3, img: img_06,roomId: 3, isFavorite: false},
    ]
  },
  {
    id: 13,
    categoryId: 2,
    subCategoryId: 2,
    typeId: 2,
    img: img_10,
    hover_Name: "Minimalist Interior Design",
    hover_About: "Lorem ipsum dolor sit amet consectetur. Euismod commodo ut mus urna justo vel Euismod commodo ut mus urna justo vel.",
    hover_See: "See Project",
    title: "Modern Minimalistic Interior Design",
    subTitle: "Lorem ipsum dolor sit amet consectetur. Integer sit vel quisque laoreet lacus at. Adipiscing lacinia sit platea a nunc libero.",
    description: "Lorem ipsum dolor sit amet consectetur. Integer sit vel quisque laoreet lacus at. Adipiscing lacinia sit platea a nunc libero. In ut adipiscing urna pellentesque amet varius posuere quis. Lorem ipsum dolor sit amet consectetur. Integer sit vel quisque laoreet lacus at. ",
    location: "Czech Republic, Prague",
    size: "80 m2",
    date: "04 / 2024",
    isFavorite: true,
    images: [
      {id: 1, img: img_04,roomId: 1, isFavorite: false},
      {id: 2, img: img_05,roomId: 2, isFavorite: false},
      {id: 3, img: img_06,roomId: 3, isFavorite: false},
    ]
  },
  {
    id: 14,
    categoryId: 2,
    subCategoryId: 2,
    typeId: 2,
    img: img_01,
    hover_Name: "Minimalist Interior Design",
    hover_About: "Lorem ipsum dolor sit amet consectetur. Euismod commodo ut mus urna justo vel Euismod commodo ut mus urna justo vel.",
    hover_See: "See Project",
    title: "Modern Minimalistic Interior Design",
    subTitle: "Lorem ipsum dolor sit amet consectetur. Integer sit vel quisque laoreet lacus at. Adipiscing lacinia sit platea a nunc libero.",
    description: "Lorem ipsum dolor sit amet consectetur. Integer sit vel quisque laoreet lacus at. Adipiscing lacinia sit platea a nunc libero. In ut adipiscing urna pellentesque amet varius posuere quis. Lorem ipsum dolor sit amet consectetur. Integer sit vel quisque laoreet lacus at. ",
    location: "Czech Republic, Prague",
    size: "80 m2",
    date: "04 / 2024",
    isFavorite: true,
    images: [
      {id: 1, img: img_04,roomId: 1, isFavorite: false},
      {id: 2, img: img_05,roomId: 2, isFavorite: false},
      {id: 3, img: img_06,roomId: 3, isFavorite: false},
    ]
  },
  {
    id: 15,
    categoryId: 2,
    subCategoryId: 2,
    typeId: 2,
    img: img_03,
    hover_Name: "Minimalist Interior Design",
    hover_About: "Lorem ipsum dolor sit amet consectetur. Euismod commodo ut mus urna justo vel Euismod commodo ut mus urna justo vel.",
    hover_See: "See Project",
    title: "Modern Minimalistic Interior Design",
    subTitle: "Lorem ipsum dolor sit amet consectetur. Integer sit vel quisque laoreet lacus at. Adipiscing lacinia sit platea a nunc libero.",
    description: "Lorem ipsum dolor sit amet consectetur. Integer sit vel quisque laoreet lacus at. Adipiscing lacinia sit platea a nunc libero. In ut adipiscing urna pellentesque amet varius posuere quis. Lorem ipsum dolor sit amet consectetur. Integer sit vel quisque laoreet lacus at. ",
    location: "Czech Republic, Prague",
    size: "80 m2",
    date: "04 / 2024",
    isFavorite: true,
    images: [
      {id: 1, img: img_04,roomId: 1, isFavorite: false},
      {id: 2, img: img_05,roomId: 2, isFavorite: false},
      {id: 3, img: img_06,roomId: 3, isFavorite: false},
    ]
  },
  {
    id: 16,
    categoryId: 2,
    subCategoryId: 2,
    typeId: 2,
    img: img_04,
    hover_Name: "Minimalist Interior Design",
    hover_About: "Lorem ipsum dolor sit amet consectetur. Euismod commodo ut mus urna justo vel Euismod commodo ut mus urna justo vel.",
    hover_See: "See Project",
    title: "Modern Minimalistic Interior Design",
    subTitle: "Lorem ipsum dolor sit amet consectetur. Integer sit vel quisque laoreet lacus at. Adipiscing lacinia sit platea a nunc libero.",
    description: "Lorem ipsum dolor sit amet consectetur. Integer sit vel quisque laoreet lacus at. Adipiscing lacinia sit platea a nunc libero. In ut adipiscing urna pellentesque amet varius posuere quis. Lorem ipsum dolor sit amet consectetur. Integer sit vel quisque laoreet lacus at. ",
    location: "Czech Republic, Prague",
    size: "80 m2",
    date: "04 / 2024",
    isFavorite: true,
    images: [
      {id: 1, img: img_04,roomId: 1, isFavorite: false},
      {id: 2, img: img_05,roomId: 2, isFavorite: false},
      {id: 3, img: img_06,roomId: 3, isFavorite: false},
    ]
  },
  {
    id: 17,
    categoryId: 2,
    subCategoryId: 2,
    typeId: 2,
    img: img_07,
    hover_Name: "Minimalist Interior Design",
    hover_About: "Lorem ipsum dolor sit amet consectetur. Euismod commodo ut mus urna justo vel Euismod commodo ut mus urna justo vel.",
    hover_See: "See Project",
    title: "Modern Minimalistic Interior Design",
    subTitle: "Lorem ipsum dolor sit amet consectetur. Integer sit vel quisque laoreet lacus at. Adipiscing lacinia sit platea a nunc libero.",
    description: "Lorem ipsum dolor sit amet consectetur. Integer sit vel quisque laoreet lacus at. Adipiscing lacinia sit platea a nunc libero. In ut adipiscing urna pellentesque amet varius posuere quis. Lorem ipsum dolor sit amet consectetur. Integer sit vel quisque laoreet lacus at. ",
    location: "Czech Republic, Prague",
    size: "80 m2",
    date: "04 / 2024",
    isFavorite: true,
    images: [
      {id: 1, img: img_04,roomId: 1, isFavorite: false},
      {id: 2, img: img_05,roomId: 2, isFavorite: false},
      {id: 3, img: img_06,roomId: 3, isFavorite: false},
    ]
  },
  {
    id: 18,
    categoryId: 2,
    subCategoryId: 2,
    typeId: 2,
    img: img_06,
    hover_Name: "Minimalist Interior Design",
    hover_About: "Lorem ipsum dolor sit amet consectetur. Euismod commodo ut mus urna justo vel Euismod commodo ut mus urna justo vel.",
    hover_See: "See Project",
    title: "Modern Minimalistic Interior Design",
    subTitle: "Lorem ipsum dolor sit amet consectetur. Integer sit vel quisque laoreet lacus at. Adipiscing lacinia sit platea a nunc libero.",
    description: "Lorem ipsum dolor sit amet consectetur. Integer sit vel quisque laoreet lacus at. Adipiscing lacinia sit platea a nunc libero. In ut adipiscing urna pellentesque amet varius posuere quis. Lorem ipsum dolor sit amet consectetur. Integer sit vel quisque laoreet lacus at. ",
    location: "Czech Republic, Prague",
    size: "80 m2",
    date: "04 / 2024",
    isFavorite: true,
    images: [
      {id: 1, img: img_04,roomId: 1, isFavorite: false},
      {id: 2, img: img_05,roomId: 2, isFavorite: false},
      {id: 3, img: img_06,roomId: 3, isFavorite: false},
    ]
  },
  {
    id: 19,
    categoryId: 2,
    subCategoryId: 2,
    typeId: 2,
    img: img_02,
    hover_Name: "Minimalist Interior Design",
    hover_About: "Lorem ipsum dolor sit amet consectetur. Euismod commodo ut mus urna justo vel Euismod commodo ut mus urna justo vel.",
    hover_See: "See Project",
    title: "Modern Minimalistic Interior Design",
    subTitle: "Lorem ipsum dolor sit amet consectetur. Integer sit vel quisque laoreet lacus at. Adipiscing lacinia sit platea a nunc libero.",
    description: "Lorem ipsum dolor sit amet consectetur. Integer sit vel quisque laoreet lacus at. Adipiscing lacinia sit platea a nunc libero. In ut adipiscing urna pellentesque amet varius posuere quis. Lorem ipsum dolor sit amet consectetur. Integer sit vel quisque laoreet lacus at. ",
    location: "Czech Republic, Prague",
    size: "80 m2",
    date: "04 / 2024",
    isFavorite: true,
    images: [
      {id: 1, img: img_04,roomId: 1, isFavorite: false},
      {id: 2, img: img_05,roomId: 2, isFavorite: false},
      {id: 3, img: img_06,roomId: 3, isFavorite: false},
    ]
  },
  {
    id: 20,
    categoryId: 2,
    subCategoryId: 2,
    typeId: 2,
    img: img_10,
    hover_Name: "Minimalist Interior Design",
    hover_About: "Lorem ipsum dolor sit amet consectetur. Euismod commodo ut mus urna justo vel Euismod commodo ut mus urna justo vel.",
    hover_See: "See Project",
    title: "Modern Minimalistic Interior Design",
    subTitle: "Lorem ipsum dolor sit amet consectetur. Integer sit vel quisque laoreet lacus at. Adipiscing lacinia sit platea a nunc libero.",
    description: "Lorem ipsum dolor sit amet consectetur. Integer sit vel quisque laoreet lacus at. Adipiscing lacinia sit platea a nunc libero. In ut adipiscing urna pellentesque amet varius posuere quis. Lorem ipsum dolor sit amet consectetur. Integer sit vel quisque laoreet lacus at. ",
    location: "Czech Republic, Prague",
    size: "80 m2",
    date: "04 / 2024",
    isFavorite: true,
    images: [
      {id: 1, img: img_04,roomId: 1, isFavorite: false},
      {id: 2, img: img_05,roomId: 2, isFavorite: false},
      {id: 3, img: img_06,roomId: 3, isFavorite: false},
    ]
  },
  {
    id: 21,
    categoryId: 2,
    subCategoryId: 2,
    typeId: 2,
    img: img_11,
    hover_Name: "Minimalist Interior Design",
    hover_About: "Lorem ipsum dolor sit amet consectetur. Euismod commodo ut mus urna justo vel Euismod commodo ut mus urna justo vel.",
    hover_See: "See Project",
    title: "Modern Minimalistic Interior Design",
    subTitle: "Lorem ipsum dolor sit amet consectetur. Integer sit vel quisque laoreet lacus at. Adipiscing lacinia sit platea a nunc libero.",
    description: "Lorem ipsum dolor sit amet consectetur. Integer sit vel quisque laoreet lacus at. Adipiscing lacinia sit platea a nunc libero. In ut adipiscing urna pellentesque amet varius posuere quis. Lorem ipsum dolor sit amet consectetur. Integer sit vel quisque laoreet lacus at. ",
    location: "Czech Republic, Prague",
    size: "80 m2",
    date: "04 / 2024",
    isFavorite: true,
    images: [
      {id: 1, img: img_04,roomId: 1, isFavorite: false},
      {id: 2, img: img_05,roomId: 2, isFavorite: false},
      {id: 3, img: img_06,roomId: 3, isFavorite: false},
    ]
  },
  {
    id: 22,
    categoryId: 2,
    subCategoryId: 2,
    typeId: 2,
    img: img_12,
    hover_Name: "Minimalist Interior Design",
    hover_About: "Lorem ipsum dolor sit amet consectetur. Euismod commodo ut mus urna justo vel Euismod commodo ut mus urna justo vel.",
    hover_See: "See Project",
    title: "Modern Minimalistic Interior Design",
    subTitle: "Lorem ipsum dolor sit amet consectetur. Integer sit vel quisque laoreet lacus at. Adipiscing lacinia sit platea a nunc libero.",
    description: "Lorem ipsum dolor sit amet consectetur. Integer sit vel quisque laoreet lacus at. Adipiscing lacinia sit platea a nunc libero. In ut adipiscing urna pellentesque amet varius posuere quis. Lorem ipsum dolor sit amet consectetur. Integer sit vel quisque laoreet lacus at. ",
    location: "Czech Republic, Prague",
    size: "80 m2",
    date: "04 / 2024",
    isFavorite: true,
    images: [
      {id: 1, img: img_04,roomId: 1, isFavorite: false},
      {id: 2, img: img_05,roomId: 2, isFavorite: false},
      {id: 3, img: img_06,roomId: 3, isFavorite: false},
    ]
  },
  {
    id: 23,
    categoryId: 1,
    subCategoryId: 3,
    typeId: 3,
    img: img_03,
    hover_Name: "Minimalist Interior Design",
    hover_About: "Lorem ipsum dolor sit amet consectetur. Euismod commodo ut mus urna justo vel Euismod commodo ut mus urna justo vel.",
    hover_See: "See Project",
    title: "Modern Minimalistic Interior Design",
    subTitle: "Lorem ipsum dolor sit amet consectetur. Integer sit vel quisque laoreet lacus at. Adipiscing lacinia sit platea a nunc libero.",
    description: "Lorem ipsum dolor sit amet consectetur. Integer sit vel quisque laoreet lacus at. Adipiscing lacinia sit platea a nunc libero. In ut adipiscing urna pellentesque amet varius posuere quis. Lorem ipsum dolor sit amet consectetur. Integer sit vel quisque laoreet lacus at. ",
    location: "Czech Republic, Prague",
    size: "80 m2",
    date: "04 / 2024",
    isFavorite: true,
    images: [
      {id: 1, img: img_07,roomId: 1, isFavorite: false},
      {id: 2, img: img_08,roomId: 2, isFavorite: false},
      {id: 3, img: img_09,roomId: 3, isFavorite: false},
    ],
  },

  {
    id: 24,
    categoryId: 2,
    subCategoryId: 4,
    typeId: 4,
    img: img_10,
    hover_Name: "Minimalist Interior Design",
    hover_About: "Lorem ipsum dolor sit amet consectetur. Euismod commodo ut mus urna justo vel Euismod commodo ut mus urna justo vel.",
    hover_See: "See Project",
    title: "Modern Minimalistic Interior Design",
    subTitle: "Lorem ipsum dolor sit amet consectetur. Integer sit vel quisque laoreet lacus at. Adipiscing lacinia sit platea a nunc libero.",
    description: "Lorem ipsum dolor sit amet consectetur. Integer sit vel quisque laoreet lacus at. Adipiscing lacinia sit platea a nunc libero. In ut adipiscing urna pellentesque amet varius posuere quis. Lorem ipsum dolor sit amet consectetur. Integer sit vel quisque laoreet lacus at. ",
    location: "Czech Republic, Prague",
    size: "80 m2",
    date: "04 / 2024",
    isFavorite: false,
    images: [
      {id: 1, img: img_10,roomId: 1, isFavorite: false},
      {id: 2, img: img_11,roomId: 2, isFavorite: false},
      {id: 3, img: img_12,roomId: 3, isFavorite: false},
    ],
  },

  {
    id: 25,
    categoryId: 2,
    subCategoryId: 4,
    typeId: 4,
    img: img_02,
    hover_Name: "Minimalist Interior Design",
    hover_About: "Lorem ipsum dolor sit amet consectetur. Euismod commodo ut mus urna justo vel Euismod commodo ut mus urna justo vel.",
    hover_See: "See Project",
    title: "Modern Minimalistic Interior Design",
    subTitle: "Lorem ipsum dolor sit amet consectetur. Integer sit vel quisque laoreet lacus at. Adipiscing lacinia sit platea a nunc libero.",
    description: "Lorem ipsum dolor sit amet consectetur. Integer sit vel quisque laoreet lacus at. Adipiscing lacinia sit platea a nunc libero. In ut adipiscing urna pellentesque amet varius posuere quis. Lorem ipsum dolor sit amet consectetur. Integer sit vel quisque laoreet lacus at. ",
    location: "Czech Republic, Prague",
    size: "80 m2",
    date: "04 / 2024",
    isFavorite: true,
    images: [
      {id: 1, img: img_10,roomId: 1, isFavorite: false},
      {id: 2, img: img_11,roomId: 2, isFavorite: false},
      {id: 3, img: img_12,roomId: 3, isFavorite: false},
    ],
  },
];
